IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'CT_REPLICATIONSTATE')
BEGIN
	CREATE TABLE CT_REPLICATIONSTATE (
		TableName VARCHAR(100) PRIMARY KEY,
		EndSync DATETIME NOT NULL DEFAULT GETUTCDATE(),
		BeginSync DATETIME NOT NULL DEFAULT GETUTCDATE(),
		LastSyncResult NVARCHAR(MAX) NULL,
		LastFullSync DATETIME NOT NULL DEFAULT DATEADD(year,-1,GETUTCDATE()),
		LastVersion BIGINT NOT NULL DEFAULT 0
	)
END