IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'CT_REPLICATIONSTATE')
BEGIN
	CREATE TABLE CT_REPLICATIONSTATE (
		TableName VARCHAR(100) PRIMARY KEY,
		LastSync DATETIME NOT NULL DEFAULT GETDATE(),
		LastHashSync DATETIME NOT NULL DEFAULT GETDATE(),
		LastVersion BIGINT NOT NULL DEFAULT 0
	)
END