	CREATE TABLE IF NOT EXISTS CT_REPLICATIONSTATE (
		TableName VARCHAR(100),
		EndSync DATETIME NOT NULL DEFAULT now(),
		BeginSync DATETIME NOT NULL DEFAULT now(),
		LastSyncResult LONGTEXT NULL,
		LastFullSync DATETIME NOT NULL DEFAULT now(),
		LastVersion BIGINT NOT NULL DEFAULT 0,
		PRIMARY KEY(TableName)
	)
